image: Visual Studio 2019

build:
  verbosity: detailed

artifacts:
  - path: /src/**/*.nupkg

build_script:
  - cmd: dotnet build src -c Release

test_script:
  - cmd: dotnet test src -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: 8G9YameBdhru/IMbVx7pYUUbJIFhY8tlknufAT3NAI/NYugtgQYBs+1Y9te1oAGK
    on:
      appveyor_repo_tag: true
